### ISSUE TITLE
Deviation of object orientation

### ISSUE THREAD

**Issue by hraban35** [MarkusA380/PersistentRotation#8] opened 2016-04-22 18:21 UTC
For inclinations deviating from 0 degrees, the orientation of the rotation Monitored object deviates. Example: If a space station prograde oriented in an orbit with an inclination of 52 degrees and "Persistant Rotation" activates (only Stability Assist) the alignment deviates with every circumnavigation.

**Comment by markusa380** [comment] 2016-09-03 11:24
On it.

**Comment by markusa380** [comment] 2016-09-03 13:12
I was able to reproduce the bug. I am investigating the cause of it.

**Comment by markusa380** [comment] 2016-09-03 17:27
Should be fixed now. If issue persists, please open an new issue.

**Closed as completed** 2016-09-03 17:27 UTC
